---
 # - debug: msg="version is {{ debian_minor_version }}"
  - name: Update repositories cache and install "java" package
    ansible.builtin.apt:
      name: openjdk-8-jdk
      update_cache: yes
    when: debian_major_version <= 6

  - name: Import PGP keys
    apt_key: 
      url: "{{ debian_PGP_key }}"
      keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

  - name: Install apt-transport-https package
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes

  - name: Insert line at end
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/elastic-{{ debian_major_version }}.x.list
      line: deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ debian_major_version }}.x/apt stable main
      create: yes

  - name: Installing specific package of Elasticsearch from debian package
    apt: 
      name: elasticsearch={{ debian_minor_version }}
      state: present
      update_cache: yes

  - name: Start service elasticsearch, if not started
    ansible.builtin.service:
      name: elasticsearch
      state: started
  
 
   

        

