---
- name: Installing JDk
  yum: 
    name: java-1.8.0-openjdk
    update_cache: yes
  when: debian_major_version <= 6
  
- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: "{{ redhat_GPG_key }}"

- name: Copying elastic.repo file
  template: 
    src: /home/sunil/elasticsearch/role/es_role/templates/elasticsearch_repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    
- name: Install the latest version of elasticsearch from the elasticsearch repo
  ansible.builtin.yum:
    name: elasticsearch-{{ redhat_minor_version }}
    enablerepo: elasticsearch
    state: present
    update_cache: yes
